In [6]:
import tensorflow as tf


#1 basic
a = tf.placeholder(tf.int32, [3])

b = tf.constant(2)
basicOp = a*b

sess = tf.Session()

r1 = sess.run(basicOp, feed_dict={a:[1,2,3]})
print(r1)

r2 = sess.run(basicOp, feed_dict={a:[4,5,6]})
print(r2)

#2 None으로 지정
c = tf.placeholder(tf.int32,[None])
nonOp = c*b

r3 = sess.run(nonOp, feed_dict={c:[7,8,9,0]})
print(r3)

r4 = sess.run(nonOp, feed_dict={c:[1]})
print(r4)

[2 4 6]
[ 8 10 12]
[14 16 18  0]
[2]
